### PR TITLE
Streamlined the usage of formal "you" 

### PR DESCRIPTION
**Pull request by heyimjonas**
Currently there is a mix of formal and informal language in the german UI, i changed it so it's fully formal now. 

If it should be informal which would also work let me know and ill change it towards that instead.

### CODE REVIEW

**Comment by joethei** [comment]
I would use the same "formality" as the translation's for the app, which is using the informal you

**Comment by kepano** [comment]
@heyimjonas agreed with joethei, we should keep it consistent with the app, see
https://github.com/obsidianmd/obsidian-translations/blob/master/de.json

**Review by kepano — CHANGES_REQUESTED** [review]
Please use tone consistent with the Obsidian app. Thanks!

**Comment by kepano** [comment]
Please resubmit when you're ready, thanks

**Pull request closed without merging**
